name: CI

on: [push, pull_request]

jobs:
    format-check:
        runs-on: ubuntu-latest

        steps:
              - name: Checkout repository
                uses: actions/checkout@v2
        
              - name: Set up Deno
                uses: denoland/setup-deno@v1
                with:
                  deno-version: v1.x
        
              - name: Check fmt
                run: deno fmt --check